export const API = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    me: '/auth/me',
    otpSend: '/auth/otp/send',
    otpVerify: '/auth/otp/verify',
  },
  me: {
    loyalty: '/me/loyalty',
    loyaltyTransactions: '/me/loyalty/transactions',
    vouchers: '/me/vouchers',
    voucher: (id: string) => `/me/vouchers/${id}`,
    vehicles: '/me/vehicles',
    vehicle: (id: string) => `/me/vehicles/${id}`,
    vehicleDefault: (id: string) => `/me/vehicles/${id}/set-default`,
    orders: '/me/orders',
    order: (id: string) => `/me/orders/${id}`,
    orderPreview: '/me/orders/preview',
    orderSlots: '/me/orders/available-slots',
    orderReschedule: (id: string) => `/me/orders/${id}/reschedule`,
    orderCancel: (id: string) => `/me/orders/${id}/cancel`,
    feedback: '/me/feedback',
    feedbackByOrder: (orderId: string) => `/me/feedback/${orderId}`,
    workOrders: '/me/work-orders',
    workOrder: (id: string) => `/me/work-orders/${id}`,
    workOrderStart: (id: string) => `/me/work-orders/${id}/start`,
    workOrderFinish: (id: string) => `/me/work-orders/${id}/finish`,
  },
  washer: {
    schedule: '/washers/me/schedule',
  },
  serviceTypes: '/service-types',
  serviceType: (id: string) => `/service-types/${id}`,
  vehicleTypes: '/vehicle-types',
  tierConfigs: '/tier-configs',
  chat: {
    message: '/chat/message',
    session: (id: string) => `/chat/sessions/${id}`,
  },
  upload: {
    image: '/upload/image',
    images: '/upload/images',
  },
} as const;
